language: php

php:
  - 7.1.3

before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --no-interaction
  - mysql -e 'create database testing;'
  - mysql -e 'create database testing_tenant;'
  - php artisan key:generate

script:
  - vendor/bin/phpunit

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

